Provide correct export types for CJS module
Since module export format is CJS, TypeScript should be informed about the fact by using `export =` instead of `export default`.

`export default` is for ES modules, and when is used to declare exports of a CJS module (which doesn't have a "default" export) in a certain build/bundle config scenarios it can create a runtime bugs (Uncaught TypeError: es2015_1.default is not a function)